/**
 * The hash chain survives being moved between deployments.
 *
 * Sanad is a product. It runs on our cloud, and on each buying institution's
 * own on-premises OpenShift under that institution's policy (E-23). So a bank
 * that pilots with us and then buys takes its data with it — and most of that
 * is an ordinary database migration.
 *
 * The leg chain is not ordinary. It is what lets the Board verify the order of
 * a Murabaha mathematically, from the documents alone, without trusting our
 * logs (SH-07). A chain that stops verifying after a move is not a migration
 * bug that shows up in testing; it shows up at the first Shariah audit after
 * go-live, against a live client's executed transactions, and there is no
 * fixing it retrospectively because the evidence of the original order is
 * precisely what was lost.
 *
 * What makes this survivable is a design choice worth naming: **the chain
 * binds content, not storage identity.** `prevLegHash` references the
 * predecessor's `contentHash` — the hash of the rendition that was actually
 * executed. It does not reference a row id, an insertion order, a sequence
 * generated by the database, or anything else a migration can change.
 *
 * These tests prove that property rather than assume it, by doing to a chain
 * the things a migration does.
 */

import { describe, expect, it } from 'vitest';

import { appendLeg, verifyChain, type ContractLeg } from '../../products/murabaha-scf/legs/leg.ts';
import { tsaInstant, type TsaInstant } from '../../core/time/tsa.ts';
import { expectOk } from '../../core/kernel/result.ts';

const at = (epochSeconds: number): TsaInstant =>
  tsaInstant({
    verified: true,
    genTimeEpochSeconds: BigInt(epochSeconds),
    tokenDigest: `tsa-${String(epochSeconds)}`,
    authorityId: 'accredited-authority',
  });

function leg(params: {
  readonly n: number;
  readonly contentHash: string;
  readonly prevLegHash?: string;
  readonly legId?: string;
}): ContractLeg {
  return {
    legId: params.legId ?? `leg-${String(params.n)}`,
    tenantId: 'bank-a',
    transactionId: 'txn-1',
    legType: (['WAAD', 'PURCHASE', 'SALE_OFFER', 'ACCEPTANCE'] as const)[params.n - 1] ?? 'DELIVERY',
    sequenceNo: params.n,
    documentId: `doc-${String(params.n)}`,
    contentHash: params.contentHash,
    ...(params.prevLegHash === undefined ? {} : { prevLegHash: params.prevLegHash }),
    executedAt: at(1_000 + params.n * 60),
    tsaTokenDigest: `tsa-${String(1_000 + params.n * 60)}`,
    templateVersionId: `tpl-v${String(params.n)}`,
    counterpartyRole: 'INSTITUTION',
    counterpartyCr: '1010000002',
    immutable: true,
  };
}

/** A four-leg chain, as executed on the source deployment. */
function executedChain(): readonly ContractLeg[] {
  let chain: readonly ContractLeg[] = [];
  const hashes = ['h-waad', 'h-purchase', 'h-offer', 'h-acceptance'];

  for (const [i, contentHash] of hashes.entries()) {
    chain = expectOk(
      appendLeg(
        chain,
        leg({
          n: i + 1,
          contentHash,
          ...(i === 0 ? {} : { prevLegHash: hashes[i - 1] }),
        }),
      ),
    );
  }
  return chain;
}

/*
 * Serialisation that survives a `bigint`.
 *
 * `JSON.stringify` throws on one — "Do not know how to serialize a BigInt" —
 * and `TsaInstant.epochSeconds` is a bigint precisely so an attested time can
 * exceed what a double represents exactly.
 *
 * So **a migration cannot naively round-trip a leg through JSON**, and the
 * failure is loud rather than silent, which is the good case. The bad case is
 * an exporter that "fixes" it with `Number(...)` and loses precision on a
 * timestamp that has contractual effect. There is a test below asserting the
 * naive path throws, so nobody discovers this by reaching for the lossy fix.
 */
const encode = (chain: readonly ContractLeg[]): string =>
  JSON.stringify(chain, (_key, value: unknown) =>
    typeof value === 'bigint' ? { __bigint__: value.toString() } : value,
  );

const decode = (wire: string): ContractLeg[] =>
  JSON.parse(wire, (_key, value: unknown) => {
    if (value !== null && typeof value === 'object' && '__bigint__' in value) {
      return BigInt((value as { __bigint__: string }).__bigint__);
    }
    return value;
  }) as ContractLeg[];

/**
 * What a migration does to a row: serialise it out, load it back, and quite
 * possibly give it a new storage identity on the way.
 */
function migrate(
  chain: readonly ContractLeg[],
  options: { readonly reassignIds?: boolean; readonly shuffle?: boolean } = {},
): readonly ContractLeg[] {
  let moved = decode(encode(chain)).map((l) =>
    options.reassignIds === true ? { ...l, legId: `imported-${l.legId}` } : l,
  );

  if (options.shuffle === true) {
    // Row order is not preserved by an export, a parallel load, or a
    // different table's physical layout. Nothing may depend on it.
    moved = [moved[2], moved[0], moved[3], moved[1]].filter(Boolean) as ContractLeg[];
    // The chain is content-linked, so the order is recoverable from the
    // hashes alone — which is the property being tested.
    const byPrev = new Map(moved.map((l) => [l.prevLegHash, l]));
    const rebuilt: ContractLeg[] = [];
    let next = moved.find((l) => l.prevLegHash === undefined);
    while (next !== undefined) {
      rebuilt.push(next);
      next = byPrev.get(next.contentHash);
    }
    moved = rebuilt;
  }

  return moved;
}

describe('SH-07 — a chain verifies after moving between deployments', () => {
  it('verifies on the source deployment', () => {
    expect(verifyChain(executedChain()).ok).toBe(true);
  });

  it('still verifies after a round trip through serialisation', () => {
    const moved = migrate(executedChain());
    expect(verifyChain(moved).ok).toBe(true);
  });

  it('still verifies when every storage identity is reassigned', () => {
    // A target database will not honour our identifiers, and should not have
    // to. If the chain depended on `legId`, this is where it would break.
    const moved = migrate(executedChain(), { reassignIds: true });
    expect(verifyChain(moved).ok).toBe(true);
    expect(moved.every((l) => l.legId.startsWith('imported-'))).toBe(true);
  });

  it('recovers its order from the hashes when row order is lost', () => {
    // An export, a parallel load, or a different physical layout all lose row
    // order. The chain is content-linked, so the order is recoverable without
    // trusting the sequence numbers or the storage.
    const moved = migrate(executedChain(), { shuffle: true, reassignIds: true });
    expect(moved.map((l) => l.contentHash)).toEqual([
      'h-waad',
      'h-purchase',
      'h-offer',
      'h-acceptance',
    ]);
    expect(verifyChain(moved).ok).toBe(true);
  });

  it('binds no storage identity into the link itself', () => {
    // The decisive structural property, stated directly: what a leg chains to
    // is a content hash and nothing else.
    const chain = executedChain();
    for (const [i, l] of chain.entries()) {
      if (i === 0) {
        expect(l.prevLegHash).toBeUndefined();
        continue;
      }
      expect(l.prevLegHash).toBe(chain[i - 1]?.contentHash);
      expect(l.prevLegHash).not.toBe(chain[i - 1]?.legId);
    }
  });
});

describe('what a migration has to know about the wire format', () => {
  /**
   * Found while writing these tests, and worth keeping as an assertion rather
   * than a comment: an exporter written the obvious way does not work.
   */
  it('cannot be round-tripped through plain JSON', () => {
    expect(() => JSON.stringify(executedChain())).toThrow(/BigInt/i);
  });

  it('keeps an attested instant exact when encoded properly', () => {
    // 2^53 + 1 seconds. A `Number` cannot hold this; the point of the bigint
    // is that the attested time is never approximated.
    const huge = 9_007_199_254_740_993n;
    const one = { ...(executedChain()[0] as ContractLeg), executedAt: tsaInstant({
      verified: true,
      genTimeEpochSeconds: huge,
      tokenDigest: 'tsa-huge',
      authorityId: 'accredited-authority',
    }) };

    const moved = decode(encode([one]))[0];
    expect(moved?.executedAt.epochSeconds).toBe(huge);
    expect(typeof moved?.executedAt.epochSeconds).toBe('bigint');
  });
});

describe('SH-07 — a moved chain still refuses what it refused before', () => {
  it('detects content altered in transit', () => {
    const moved = [...migrate(executedChain())];
    moved[2] = { ...(moved[2] as ContractLeg), contentHash: 'h-offer-tampered' };

    const result = verifyChain(moved);
    expect(result.ok).toBe(false);
    if (!result.ok) expect(result.error.reason).toBe('HASH_CHAIN_BROKEN');
  });

  it('detects a leg dropped in transit', () => {
    // The most plausible migration accident: a partial load. It must not
    // produce a chain that verifies with a hole in it.
    const moved = migrate(executedChain()).filter((l) => l.legType !== 'SALE_OFFER');

    const result = verifyChain(moved);
    expect(result.ok).toBe(false);
    if (!result.ok) expect(result.error.reason).toBe('HASH_CHAIN_BROKEN');
  });

  it('detects a leg reordered without relinking', () => {
    const moved = [...migrate(executedChain())];
    const swapped = [moved[0], moved[2], moved[1], moved[3]].filter(Boolean) as ContractLeg[];

    expect(verifyChain(swapped).ok).toBe(false);
  });

  it('retains the timestamping attestation across the move', () => {
    /*
     * The attestations are third-party signed, so they survive a move —
     * provided the token itself is retained and not merely its digest. The
     * domain carries `tsaTokenDigest`; the token is stored alongside, in
     * object storage under write-once retention.
     *
     * This asserts the digest survives. **Whether the retained token is
     * actually migrated with it is an operational question this test cannot
     * reach**, and it is the part most likely to be forgotten — a database
     * migration that leaves the object store behind produces a chain that
     * verifies internally and cannot be proven to a third party. Recorded as
     * E-24.
     */
    const original = executedChain();
    const moved = migrate(original, { reassignIds: true, shuffle: true });

    expect(moved.map((l) => l.tsaTokenDigest)).toEqual(original.map((l) => l.tsaTokenDigest));
    expect(moved.map((l) => l.executedAt.epochSeconds)).toEqual(
      original.map((l) => l.executedAt.epochSeconds),
    );
  });
});
