#!/usr/bin/env bash
# Generates the development secrets for a local Document Engine and the matching
# credential lines for the ops app. Writes two gitignored files; prints nothing secret.
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
COMPOSE_ENV="${ROOT}/adapters/nutrient/compose/.env"
LOCAL_ENV="${ROOT}/.env.local"
TMP="$(mktemp -d)"; trap 'rm -rf "${TMP}"' EXIT

openssl genpkey -algorithm RSA -pkeyopt rsa_keygen_bits:2048 -out "${TMP}/jwt.key" 2>/dev/null
openssl rsa -in "${TMP}/jwt.key" -pubout -out "${TMP}/jwt.pub" 2>/dev/null
API_TOKEN="$(openssl rand -hex 32)"
SECRET_KEY_BASE="$(openssl rand -hex 48)"
DASH_PW="$(openssl rand -hex 12)"
PG_PW="$(openssl rand -hex 16)"
PUB_ONE_LINE="$(awk 'NF {printf "%s\\n", $0}' "${TMP}/jwt.pub")"
PRIV_B64="$(base64 < "${TMP}/jwt.key" | tr -d '\n')"

{
  echo "# generated by scripts/nutrient-dev-keys.sh — development only, gitignored"
  echo "ACTIVATION_KEY="
  echo "API_AUTH_TOKEN=${API_TOKEN}"
  echo "SECRET_KEY_BASE=${SECRET_KEY_BASE}"
  echo "JWT_PUBLIC_KEY=\"${PUB_ONE_LINE}\""
  echo "DASHBOARD_PASSWORD=${DASH_PW}"
  echo "PGPASSWORD=${PG_PW}"
} > "${COMPOSE_ENV}"

touch "${LOCAL_ENV}"
# A Web SDK licence key already saved is kept: it comes from the vendor, not from this script.
EXISTING_WEB_KEY="$(grep '^SANAD_CREDENTIAL_DOCUMENT_PLATFORM_SANDBOX_WEB_SDK_LICENSE_KEY=' "${LOCAL_ENV}" | head -1 | cut -d= -f2- || true)"
grep -v '^SANAD_CREDENTIAL_DOCUMENT_PLATFORM_SANDBOX_' "${LOCAL_ENV}" > "${TMP}/local" || true
{
  cat "${TMP}/local"
  echo "SANAD_CREDENTIAL_DOCUMENT_PLATFORM_SANDBOX_WEB_SDK_LICENSE_KEY=${EXISTING_WEB_KEY}"
  echo "SANAD_CREDENTIAL_DOCUMENT_PLATFORM_SANDBOX_DOCUMENT_ENGINE_BASE_URL=http://127.0.0.1:5000"
  echo "SANAD_CREDENTIAL_DOCUMENT_PLATFORM_SANDBOX_DOCUMENT_ENGINE_API_TOKEN=${API_TOKEN}"
  echo "SANAD_CREDENTIAL_DOCUMENT_PLATFORM_SANDBOX_JWT_PRIVATE_KEY=${PRIV_B64}"
} > "${LOCAL_ENV}"

echo "wrote ${COMPOSE_ENV#${ROOT}/} and the four credential lines in .env.local"
echo "next: open .env.local in your editor (for example: code .env.local) and put the Web SDK licence key after the = on its line;"
echo "      the Document Engine stack needs ACTIVATION_KEY in compose/.env and is optional until you hold one"
